project_id = "dldrgctgwxhdtejeklab"

[functions.send-confirmation]
verify_jwt = false

[functions.run-reminders]
verify_jwt = false

[functions.admin-prospects]
verify_jwt = false

[functions.process-trial-pipeline]
verify_jwt = false

[functions.reprogramar-api]
verify_jwt = false