
ALTER TABLE public.leads_verano 
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS deposito_monto INTEGER,
  ADD COLUMN IF NOT EXISTS deposito_pagado BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS deposito_fecha TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS deposito_metodo TEXT,
  ADD COLUMN IF NOT EXISTS saldo_monto INTEGER,
  ADD COLUMN IF NOT EXISTS saldo_pagado BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS saldo_fecha TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS saldo_metodo TEXT,
  ADD COLUMN IF NOT EXISTS notas TEXT;
